### ISSUE TITLE
Weave sometimes fails to load save files and new games properly.

### ISSUE THREAD

**Issue by Verrasev** [computirman/weave-zzt#12]
When I run Castleweavia in the latest version of Zeta, sometimes Weave fails to load anything other than the zzt file.  That is, it doesn't load the configuration files or anything else.  This may be caused specifically by the way it interacts with Zeta but I haven't pinned it down yet and that may be beyond my skill level.

**Comment by computirman** [comment]
That's a good start - next let's try and get some repro steps.

* Is this only when you are running Zeta Standalone in Windows, or also when you are running it on the web? 
* Can you get the output of the Zeta console when it fails to load the configuration files? It will have messages that look like this:

`port in 03D8`
`port out 03D8 = 0000`
`open: file not found: CASTLEWV.PAL`
`open: file not found: CASTLEWV.HI`

Ideally I can get the complete console log from you when it happens, not just the last part.

**Comment by Verrasev** [comment]
It happens in both versions, as far as I can tell.  It happened on the home version on my computer and Dr. Dos had it happen on the web version.

**Comment by computirman** [comment]
Ok - I noted a few places where file handling had the potential to go sideways and have repaired it to the best of my ability. The version where it is fixed is 3.0k - provided I didn't introduce any regressions, this will replace 3.0j as the most recent stable version of Weave.

Will leave this issue open until confirmation.

**Comment by computirman** [comment]
This is working correctly in 3.0k and in versions 3.2 and 3.3 of Weave. Closing.
