### ISSUE TITLE
Option to remove choices from title screen

### ISSUE THREAD

**Issue by pshaughn** [computirman/weave-zzt#17]
When trying to pitch a Weave game to people unfamiliar with ZZT's history, the number of title screen options is distracting. "Scores" aren't necessarily used in a given game, and the speed setting is mostly trap choices. Hiding these seems like a good idea. In a browser context, the Quit option is likewise a trap choice... and a game might not necessarily allow saving to have games to restore... and #startgame means there might be some other way to start besides pressing P... I could see a case for keeping the license info front and center and not disabling that, but everything else seems like there's a use case for optionality.

**Comment by computirman** [comment]
Thoughts:
If the weaveZZT .CFG defines the SPEED and the game is in Release mode, then the Speed selector should be gone. **(add to 3.3j)**
If the game's .CFG disables saving and the game is in Release mode, then the Restore button should be gone. (already true)
If the game's .CFG disables high scores **(will be added in 3.3j)**, then the option to input a score on dying or leaving the game should be gone, and the high scores view option should be missing from the title screen.
If the weaveZZT .CFG identifies the game as being in WEBRELEASE mode **(will be added in 3.3j)** then 'Q'uit will be gone from the title screen.
If the weaveZZT .CFG identifies the game as being in TITLEONLY mode **(will be added in 3.3j)** then the 'P'lay option will be gone from the title screen.

**Comment by computirman** [comment]
Everything listed above is now in 3.3j.
