### ISSUE TITLE
Consistency over world reloading

### ISSUE THREAD

**Issue by pshaughn** [computirman/weave-zzt#21]
Currently: let time pass on the title board, press P, play a little, press escape Y, SOMETIMES the title screen is reset and sometimes it continues where it left off.
Desired: Guaranteed reset (maybe only with an INI flag, in case there are worlds that like sometimes not reloading?).

Alternately, sending ALL:ENTER when returning to a title board in progress would also satisfy my immediate use case (which is mostly just restarting the music at the beginning).

**Comment by computirman** [comment]
For 3.3j:
if HasINI is set and the ?+debug cheat has not been used, then quitting the game will _always_ reload the title screen.

**Comment by computirman** [comment]
In conjunction with allowing @INPUT to receive keypress events from MONITOR, this has really improved the possibility of using the controller as the sole source of input for weave games.

**Comment by computirman** [comment]
3.3j is released and this is in place; closing.
