### ISSUE TITLE
avoid redundant SetBlink calls

### ISSUE THREAD

**Issue by pshaughn** [computirman/weave-zzt#23]
SetBlink makes Zeta print two lines to stderr about port 03D8 every time it's called, which adds up if it's happening needlessly.
You've already posted a fix in Discord for this. I don't see that fix in the tree here, so I'm just putting up an issue in case you forget while you're rolling up 3.3j.

**Comment by computirman** [comment]
Good looking out. This fix will be in 3.3j.

**Comment by computirman** [comment]
3.3j is released; closing.
